version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT_APP}:${PORT_APP}
      - 5020:5020
    command: yarn dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postgres:
    container_name: postgres
    image: postgres:14
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: admin
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5433:5433
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata: